### ISSUE TITLE
import { Geolocation } from "react-native-amap-geolocation"  报错 

### ISSUE THREAD

**Issue by wangkai63** [qiuxiang/react-native-amap-geolocation#1]
大牛好，现在遇到问题如下：
1. npm install react-native-amap-geolocation
2.react-native link
3.在页面 import { Geolocation } from "react-native-amap-geolocation" 
错误提示 ‘react-native-amap-geolocation’  does not exist
在react-native-amap-geolocation 库中 android目录下并未发现index.js 或index.ts 文件的存在， 是否忘记暴露模块了。

**Comment by qiuxiang** [comment]
确实有问题，刚发布了一个修正版本。
