### ISSUE TITLE
在Android手机上有时候会出现getTime() on a null object

### ISSUE THREAD

**Issue by 25juan** [qiuxiang/react-native-amap-geolocation#10]
感谢作者为RN 生态提供地位插件。
由于本人在开发的时候用了两台手机，一台Android7，一台Android5，
在Android7中用该定位有时候会出现如下问题，但是同样的代码在Android5中没有这个问题。
请问这种改怎么处理
![image](https://user-images.githubusercontent.com/14308183/41718794-a95d4712-7590-11e8-84c3-e0ab139ed90d.png)

**Comment by qiuxiang** [comment]
稍后处理

**Comment by 25juan** [comment]
@qiuxiang  好的
