### ISSUE TITLE
RN0.61版本兼容

### ISSUE THREAD

**Issue by sunlei4076** [qiuxiang/react-native-amap-geolocation#106]
**为了节省大家的时间，请尽可能详细地说明问题，并最好提供截图（特别是出错信息）。**
升级RN0.61后
无论是add Files方式
还是cocoa pods都会报错，
有老哥们出个集成方式吗

**Comment by evan0204** [comment]
> **为了节省大家的时间，请尽可能详细地说明问题，并最好提供截图（特别是出错信息）。**
> 升级RN0.61后
> 无论是add Files方式
> 还是cocoa pods都会报错，
> 有老哥们出个集成方式吗

我刚试了下，直接集成成功了。
npm i 之后，在Podfile中自己添加
`  pod 'react-native-amap-geolocation', path: '../node_modules/react-native-amap-geolocation/lib/ios'`

然后pod install 后 run 一次就搞定了。So easy！

**Comment by sunlei4076** [comment]
移除MapFoundationKit.framework 和 AMapLocationKit.framework后
是没问题了
