### ISSUE TITLE
根据高德地图手动部署以及作者的教程文档，ios依然会报错啊，有人知道问题在哪里吗？

### ISSUE THREAD

**Issue by quietautumn** [qiuxiang/react-native-amap-geolocation#108]
**为了节省大家的时间，请尽可能详细地说明问题，并最好提供截图（特别是出错信息）。**
运行环境
 Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
报错信息：
![52EC01D8-F38E-409F-808F-B41A1706284F](https://user-images.githubusercontent.com/16301518/68008478-0f296b00-fcba-11e9-9ba1-140aa7f23648.png)
配置项:
![580DD124-2093-4DAA-BC7F-85FFDB2A03D4](https://user-images.githubusercontent.com/16301518/68008527-3122ed80-fcba-11e9-8e86-7233ee9e3807.png)

**Comment by wvalen** [comment]
https://blog.csdn.net/u011149565/article/details/90216803

**Comment by song7788q** [comment]
#103 有可能是这个问题导致的
