### ISSUE TITLE
后台定位

### ISSUE THREAD

**Issue by fgxls** [qiuxiang/react-native-amap-geolocation#11]
大佬 我看来高德地图api后在您的代码里加了几句允许后台定位的话
 然后使用的时候报这个错
Sending `AMapGeolocation` with no listeners registered.
我不知道该怎么添加listener了 需要帮助

**Comment by fgxls** [comment]
现在定位是打开了
![491529632357_ pic](https://user-images.githubusercontent.com/26613491/41754943-63ac15dc-7607-11e8-8822-9c54c38018ad.jpg)

**Comment by fgxls** [comment]
额 好像我自己比较水 解决啦

**Comment by fgxls** [comment]
但是还是不能一直获取位置 我的console只有3次 好奇怪

**Comment by qiuxiang** [comment]
有时间我再测试后台定位的情况，但我隐隐觉得 RN 生命周期会是个问题。

**Comment by qiuxiang** [comment]
<img src="https://user-images.githubusercontent.com/1709072/44764575-fcca1380-ab82-11e8-8d03-55a4e8f249ab.png" width=300>

https://github.com/qiuxiang/react-native-amap-geolocation/blob/master/docs/geolocation.md#types

**Comment by sej1228** [comment]
> 额 好像我自己比较水 解决啦

请问怎么解决的？
