### ISSUE TITLE
调用getCurrentPostion() ios返回内容和android返回内容不一致 ios 返回信息有问题

### ISSUE THREAD

**Issue by TopGuo** [qiuxiang/react-native-amap-geolocation#113]
**为了节省大家的时间，请尽可能详细地说明问题，并最好提供截图（特别是出错信息）。**
![image](https://user-images.githubusercontent.com/30146744/71070335-89a04280-21b5-11ea-9dad-76e023906016.png)

**Comment by TopGuo** [comment]
真机上 经纬度正确了 但是没有Android返回的信息全面

**Comment by qiuxiang** [comment]
逆地理编码只在国内才有
