### ISSUE TITLE
安卓运行报错误: AMapGeolocationPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()

### ISSUE THREAD

**Issue by orzhtml** [qiuxiang/react-native-amap-geolocation#114]
**为了节省大家的时间，请尽可能详细地说明问题，并最好提供截图（特别是出错信息）。**
node_modules/react-native-amap-geolocation/lib/android/src/main/java/cn/qiuxiang/react/geolocation/AMapGeolocationPackage.java:12: 错误: AMapGeolocationPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class AMapGeolocationPackage implements ReactPackage {
       ^
1 个错误
:react-native-amap-geolocation:compileDebugJavaWithJavac FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-amap-geolocation:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap-geolocation/pull/115
