### ISSUE TITLE
荣耀畅玩6X BLN-AL10 手机，如果把定位关了，不能通过网络位置获取信息

### ISSUE THREAD

**Issue by Warlock1994** [qiuxiang/react-native-amap-geolocation#13]
能不能给个提示检测Android手机有没有打开GPS，有些手机关了GPS定位特别慢。。。。

**Comment by qiuxiang** [comment]
关闭定位不能定位这是手机或 SDK 的问题，至少在我的手机不存在这个问题；网络定位慢那也是 SDK 的问题。

检查 GPS 的接口 SDK 没有提供，也暂时没打算实现，你需要找其他实现方法。
