### ISSUE TITLE
android10已经开启定位权限还是报错

### ISSUE THREAD

**Issue by wcly** [qiuxiang/react-native-amap-geolocation#140]
报错信息如下
![image](https://user-images.githubusercontent.com/23275036/113985977-5177b400-987f-11eb-9c88-c11259f8fc86.png)

**Comment by wcly** [comment]
在`android/app/src/main/AndroidManifest.xml`添加如下权限可以解决
```xml
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
```

**Comment by z3season** [comment]
> 在`android/app/src/main/AndroidManifest.xml`添加如下权限可以解决
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
> ```
添加了 还是一样报这个错

**Comment by z3season** [comment]
原来是手机的GPS按钮没有打开的问题 哈哈
