### ISSUE TITLE
ios pod install error ,如何解决？

### ISSUE THREAD

**Issue by chinajuns** [qiuxiang/react-native-amap-geolocation#15]
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-amap-geolocation` from `../node_modules/react-native-amap-geolocation/lib/ios`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing AMapFoundation (1.5.3)
Installing AMapLocation (2.6.0)
Using DoubleConversion (1.1.5)
Using Folly (2016.10.31.00)
Installing React 0.56.0
Using boost-for-react-native (1.63.0)
Using glog (0.3.4)
Installing react-native-amap-geolocation (0.3.1)
Using yoga (0.56.0.React)
重点错误地方：[!] The 'Pods-ddh' target has transitive dependencies that include static binaries: (/Users/sea/Desktop/ddh/ios/Pods/AMapLocation/AMapLocationKit.framework)

页面引用：import {GeoLocation} from 'react-native-amap-geolocation';//编译提示geolocation.js
const eventEmitter = new NativeEventEmitter(AMapGeolocation)  
NativeEventEmitter can not be null

**Comment by qiuxiang** [comment]
RN 0.56.0 暂时没有测试，podfile 的写法可能有所区别，请参考 RN 官方文档
