### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. 

### ISSUE THREAD

**Issue by orzhtml** [qiuxiang/react-native-amap-geolocation#150]
ios报错：Invariant Violation: new NativeEventEmitter() requires a non-null argument.
安卓报警告：`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

ios 是 pod 不了对应的项目

import { init } from "react-native-amap-geolocation";

await init({
  ios: "9bd6c82e77583020a73ef1af59d0c759",
  android: "043b24fe18785f33c491705ffe5b6935",
});

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M2
    Memory: 84.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.5.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: EAP AI-221.5921.22.2211.8786657 AI-221.5921.22.2211.8786657
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by orzhtml** [comment]
@qiuxiang 有空的话麻烦更新下，谢谢，辛苦你了

**Comment by orzhtml** [comment]
ios需要修改下：react-native-amap-geolocation.podspec
将它放到根目录
react-native-amap-geolocation/react-native-amap-geolocation.podspec

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = package['name']
  s.version      = package['version']
  s.summary      = package['description']
  s.authors      = { '7c00' => 'i@7c00.cc' }
  s.homepage     = package['repository']['url']
  s.license      = { :type => package['license']}
  s.platform     = :ios, "8.0"
  s.source       = { :git => package['repository']['url'] }
  s.source_files  = "lib/ios/*.{h,m}"

  s.dependency 'React'
  s.dependency 'AMapLocation', "~> 2.6.0"
end

```

**Comment by qiuxiang** [comment]
发布了，你试试看

**Comment by CHU295** [comment]
> 发布了，你试试看

我现在还有这个报错，用的最新版本，咋回事？
