### ISSUE TITLE
Android11 打包之后的apk包 无法获取到定位信息

### ISSUE THREAD

**Issue by Niceyaa** [qiuxiang/react-native-amap-geolocation#153]
Android： 11 
react-native-amap-geolocation：^1.1.2

问题描述：
              在使用react-native-amap-geolocation进行安卓定位的时候，调试阶段没问题，定位权限提示也可以出来，获取到的定位信息也能够拿到并且显示，但是打包到成apk之后，在安卓上就无法获取到定位信息了

代码：
import {init, Geolocation, setAllowsBackgroundLocationUpdates,start,stop,setDistanceFilter,setInterval,addLocationListener} from 'react-native-amap-geolocation';

export const getLocation = () => {
    return new Promise((resolve, reject) => {
        Geolocation.getCurrentPosition(async (location) => {
        // RNGeoLocation.getCurrentPosition(async (location) => {
            const {coords} = location;
            if (coords) {
                let {longitude, latitude} = coords;
              
                resolve(`${longitude},${latitude}`);
            }
        }, (err) => {
            console.log('获取失败', err);
        }, {
            enableHighAccuracy: true,
        });
    });
};
export const initGeo = async () => {
    if (Platform.OS === 'android') {
        try {
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
            );
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                await init({
                    android: mapConfig.androidKey,
                });
                return Promise.resolve();
            }
        } catch (error) {
        }
    }
};

export const getCityPosition = async () => {
    const longLat = await getLocation();
    try {
        const res = await axios.get('https://restapi.amap.com/v3/geocode/regeo', {
            params: {
                location: longLat,
                key: mapConfig.webKey,
            },
        });
        console.log('res', res.data);
        let {
            formatted_address: formattedAddress,
            addressComponent,
            status,
        } = res.data.regeocode;
        let {district, streetNumber, township} = addressComponent;
        let showPosition = `${district}${township}${streetNumber.street}${streetNumber.number}`;
        // let showPosition = `${district}${township}`
        console.log('位置信息', addressComponent);
        console.log('位置信息', formattedAddress);
        return Promise.resolve({
            formattedAddress,
            addressComponent,
            status,
            showPosition,
            longLat,
        });
        // console.log('位置信息', res.data.regeocode)
    } catch (error) {
        console.log('错误了', error);
    }
};

调用：
useEffect(() => {
        async function getLocationFn() {
            await initGeo();
            try {
                let {showPosition, longLat, addressComponent} = await getCityPosition();
                setInitLocation(showPosition);
                console.log('addressComponent', addressComponent);
                dispatch(changeCurLocationInfo(addressComponent));
                let [longitude, latitude] = longLat.split(',');
                console.log('positionInfo', addressComponent);
                setCarLat(Number(latitude));
                setCarLong(Number(longitude));
            } catch (err) {
            }
        }
        getLocationFn();
    }, []);

望各位大佬赐教

**Comment by hellogit2021** [comment]
怎么解决的，我遇到同样问题了，我用的最新的包，也是调试可以，APK就不行

**Comment by zl612** [comment]
咋解决呀
