### ISSUE TITLE
[建议] pod install 之后的duplicate错误，不能archive等问题的修复方案

### ISSUE THREAD

**Issue by MirGhojam** [qiuxiang/react-native-amap-geolocation#16]
## 运行环境
macOS High Sierra 10.13.6
* 插件版本: 2.2.7
* react-native 版本：0.55.4

## 期望效果
应用能在debug和release环境中运行并且能archive

## 实际效果
若debug环境运行成功则不能release，反之亦然。不能archive

## 重现步骤
原有的RN项目中按照此插件readme集成

## Debug logs
各种duplicate error， linker error

修复方案：跟随下面链接里的最火答案，祝你们愉快（答案里的图片很重要）
https://github.com/facebook/react-native/issues/15838

**Comment by SiJieMa** [comment]
这个问题太坑了。。。
