### ISSUE TITLE
应用商店审核提示：同意隐私政策前，“AutoNaviMapView-Base”读写手机外置存储信息

### ISSUE THREAD

**Issue by SpringAndMay** [qiuxiang/react-native-amap-geolocation#162]
前端代码是在同意隐私政策后执行的init()方法，但是应用商店审核仍然提示，函数调用栈，执行了行为“READ_EXTERNAL_STORAGE/WRITE_EXTERNAL_STORAGE”：
`java.io.File.mkdir()
com.autonavi.base.amap.mapcore.FileUtil.getMapBaseStorage(FileUtil.java:133)
com.amap.api.mapcore.util.eq.a(Util.java:387)
com.amap.api.mapcore.util.eq.c(Util.java:418)
com.amap.api.mapcore.util.ba.a(OfflineDownloadManager.java:144)
com.amap.api.maps.offlinemap.OfflineMapManager.a(OfflineMapManager.java:171)
com.amap.api.maps.offlinemap.OfflineMapManager.<init>(OfflineMapManager.java:54)
cn.qiuxiang.react.amap3d.AMapOfflineModule.<init>(AMapOfflineModule.kt:12)
cn.qiuxiang.react.amap3d.AMap3DPackage.createNativeModules(AMap3DPackage.kt:12)
com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1298)
com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1269)
com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1194)
com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:132)
com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:996)`

**Comment by qiuxiang** [comment]
你这是因为 amap3d 这个包，和这个项目没关系，看调用的模块，amap3d 这个包你用了很旧的版本，那个版本还不支持隐私政策接口

**Comment by yt303085600** [comment]
感谢，我这就去试试

**Comment by SpringAndMay** [comment]
> 你这是因为 amap3d 这个包，和这个项目没关系，看调用的模块，amap3d 这个包你用了很旧的版本，那个版本还不支持隐私政策接口

感谢，我这就去试试
