### ISSUE TITLE
 Could not find method namespace() for arguments [cn.qiuxiang.react.geolocation] on extension 'android' of type com.android.build.gradle.LibraryExtension.

### ISSUE THREAD

**Issue by inkcrazy666** [qiuxiang/react-native-amap-geolocation#168]
"react": "16.11.0",
"react-native": "0.63.5",

* What went wrong:
A problem occurred evaluating project ':react-native-amap-geolocation'.
> Could not find method namespace() for arguments [cn.qiuxiang.react.geolocation] on extension 'android' of type com.android.build.gradle.LibraryExtension.

**Comment by qiuxiang** [comment]
新的 gradle 配置要比较新的版本，算了，我先改回去，之后再发 breaking change 版本

**Comment by inkcrazy666** [comment]
好的谢谢大佬，预计需要最低什么版本？

**Comment by qiuxiang** [comment]
修正发布了
