### ISSUE TITLE
ios无法获取城市信息

### ISSUE THREAD

**Issue by keyWung** [qiuxiang/react-native-amap-geolocation#17]
如题，以正确配置key，安卓可以获取定位到的城市信息，ios获取不到，只有经纬度信息

**Comment by keyWung** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/6467137/43525985-b8730df8-95d5-11e8-96c2-14d325c5b964.png">

**Comment by jialongsu** [comment]
同学，这个问题解决了吗，我也遇到了，key是正确的，android是可以正常返回城市信息，ios只有经纬度

**Comment by keyWung** [comment]
没有呢

**Comment by qiuxiang** [comment]
我注意到了，截图的坐标是国外的，国外坐标不支逆地理编码

**Comment by keyWung** [comment]
为什么会出现外国的坐标呢？

**Comment by qiuxiang** [comment]
你这是模拟器吧

**Comment by keyWung** [comment]
是的，不过用真机测试也是这样，返回的坐标是正确的，就是没有城市返回

**Comment by fgxls** [comment]
我用的半年的app上周开始也只有经纬度信息了，用户投诉了无数次。。。
今天才查出来是这个问题，因为debug安装没问题，只有release才这样，完全懵逼

**Comment by qiuxiang** [comment]
debug 和 release 的 key 不一样

**Comment by zyp0930** [comment]
![96ec3ee656be1ba09711467afd40bd37](https://user-images.githubusercontent.com/43630403/46123529-9e5f8600-c251-11e8-9ff1-1c658ef427b7.jpg)
iOS获取不到城市信息，但是安卓是可以正常获取的

**Comment by plimerence** [comment]
same issues,even if I config like this ` [_manager  setLocatingWithReGeocode:YES];
    //设置期望定位精度
    [_manager setDesiredAccuracy:kCLLocationAccuracyHundredMeters];
    //设置不允许系统暂停定位
    [_manager setPausesLocationUpdatesAutomatically:NO];
    //设置允许在后台定位
    [_manager setAllowsBackgroundLocationUpdates:YES];
    //设置定位超时时间
    [_manager setLocationTimeout:DefaultLocationTimeout];
    //设置逆地理超时时间
    [_manager setReGeocodeTimeout:DefaultReGeocodeTimeout];`

最终办法我使用[_manager requestLocationWithReGeocode:YES completionBlock:self.completionBlock];  这个函数可以获取到省份信息 ，我猜测或许是高德那边做了变动了吧，官方的api也是支持这种方式获取

**Comment by Just013** [comment]
> 如题，以正确配置key，安卓可以获取定位到的城市信息，ios获取不到，只有经纬度信息

我跟你一样的问题，你现在解决了吗？

**Comment by WuPan1018** [comment]
是的，不过用真机测试也是这样，返回的坐标是正确的，但是iOS没有城市返回

**Comment by meiqi1992** [comment]
+1

**Comment by meiqi1992** [comment]
_manager.locatingWithReGeocode=YES 可以获取到位置信息

**Comment by TheSixer** [comment]
> _manager.locatingWithReGeocode=YES 可以获取到位置信息

it doesn't work.

**Comment by inkCrazy** [comment]
找到问题了，node_modules->react-native-amap-geolocation->lib->ios->RCTGeolocationModule.m
RCT_EXPORT_METHOD(start) {
    if (_manager.locatingWithReGeocode) {
        [_manager setLocatingWithReGeocode:YES];
    }
    [_manager startUpdatingLocation];
}中添加
if (_manager.locatingWithReGeocode) {
        [_manager setLocatingWithReGeocode:YES];
    }
我具体是参考官方的配置流程发现问题的：https://lbs.amap.com/api/ios-location-sdk/guide/get-location/backgroundlocation/
其他具体的配置细节，大家可以自由添加
实验结果如图：
![c25ea033-71c1-429c-8bd1-99439455542d](https://user-images.githubusercontent.com/12253453/51664909-80364680-1ff5-11e9-866c-208fbe59214c.png)

**Comment by inkCrazy** [comment]
找到问题了，node_modules->react-native-amap-geolocation->lib->ios->RCTGeolocationModule.m
RCT_EXPORT_METHOD(start) {
    if (_manager.locatingWithReGeocode) {
        [_manager setLocatingWithReGeocode:YES];
    }
    [_manager startUpdatingLocation];
}中添加
if (_manager.locatingWithReGeocode) {
        [_manager setLocatingWithReGeocode:YES];
    }
我具体是参考官方的配置流程发现问题的：https://lbs.amap.com/api/ios-location-sdk/guide/get-location/backgroundlocation/
其他具体的配置细节，大家可以自由添加
实验结果如图：
![c25ea033-71c1-429c-8bd1-99439455542d](https://user-images.githubusercontent.com/12253453/51664909-80364680-1ff5-11e9-866c-208fbe59214c.png)

**Comment by inkCrazy** [comment]
突然发现和[_manager setLocatingWithReGeocode:YES];没关系，这是官方的说明：https://lbs.amap.com/faq/location/location-develop/emptyaddress/?wd=%E9%80%86%E5%9C%B0%E7%90%86%E7%BC%96%E7%A0%81&cateId=&page=&detail=true
官方的意思是异步的需要几次才会有逆地理位置信息(我自己测试下来第四次才有)，但是为什么就是iOS很奇怪，作者写的是持续定位的方案，所以我就条件控制有地理位置信息的时候才Geolocation.stop();
![image](https://user-images.githubusercontent.com/12253453/51719425-65f77980-2084-11e9-815f-11d57b2f1e1b.png)

**Comment by qiuxiang** [comment]
@inkCrazy 你提到的应该就是原因，我自己在 example 测试时总是可以得到地址信息的，因为是连续定位我没有意识到某次可能不返回地信息吧。

**Comment by conanma** [comment]
@qiuxiang  安卓你地理位置代码能提供一下吗 我ios可以 安卓却拿不到真实地址

**Comment by qiuxiang** [comment]
@conanma https://github.com/qiuxiang/react-native-amap-geolocation/blob/master/index.js

**Comment by wvalen** [comment]
解决方式有点笼统，可能跟我一样不懂ios源生开发的RN开发者看不懂，我在这里稍微提示一下。
Add **_manager.locatingWithReGeocode = YES** to ios/Libraries/AMapGeolocation.xcodeproj/AMapGeolocation.m

`if (!_manager) {
   //XXXXX;
   _manager.locatingWithReGeocode = YES;
}
`
