### ISSUE TITLE
init 输入高德的key以后报错.

### ISSUE THREAD

**Issue by xucongyong** [qiuxiang/react-native-amap-geolocation#171]
expo里面的app.json文件设置好了.返回的权限也是允许.
用高德的时候,init 输入高德的key以后报错.
init不存在

![61decf55aa67b451d6542791a93e2ba3](https://github.com/qiuxiang/react-native-amap-geolocation/assets/22570151/89f679e8-5138-4838-a402-9c72d1798129)

**Comment by lengziyu** [comment]
老哥请问一下，在expo使用这个npm包，如果使用？解决了吗？
