### ISSUE TITLE
苹果审核要求移除UIBackgroundModes：location，我0.63.5的项目移除没事，0.68.5移除就报错了

### ISSUE THREAD

**Issue by inkcrazy666** [qiuxiang/react-native-amap-geolocation#174]
两个项目都是minimum deployments：iOS11.0
运行在iPhone 14的模拟器

![截屏2023-08-25 09 09 39](https://github.com/qiuxiang/react-native-amap-geolocation/assets/130324703/8559b7ef-e5cd-48e1-8df5-6983d00d74ef)

没报错的项目：

```  
  "react": "16.11.0",
    "react-native": "0.63.5",
    "react-native-amap-geolocation": "^1.2.3",
    "react-native-amap3d": "^3.2.4",
```

![截屏2023-08-25 09 00 52](https://github.com/qiuxiang/react-native-amap-geolocation/assets/130324703/dd231b0f-3b5f-4d70-a956-13ef6ebfe45a)

报错的项目：
```
    "react": "17.0.2",
    "react-native": "0.68.5",
    "react-native-amap-geolocation": "^1.2.3",
```

![截屏2023-08-25 09 00 28](https://github.com/qiuxiang/react-native-amap-geolocation/assets/130324703/def96974-c633-44f6-b1c7-cde2bf1a0f18)

![Simulator Screenshot - iPhone 14 - 2023-08-25 at 08 53 52](https://github.com/qiuxiang/react-native-amap-geolocation/assets/130324703/7efded6a-1dc7-4e69-b4d1-d68b4fb297c2)

**Comment by inkcrazy666** [comment]
我自己傻逼，初始化的时候写了：setAllowsBackgroundLocationUpdates(true);

**Comment by chj-damon** [comment]
感谢感谢，我也遇到同样的问题了
