### ISSUE TITLE
没有监听到定位返回的数据

### ISSUE THREAD

**Issue by lytian** [qiuxiang/react-native-amap-geolocation#18]
我把你这个项目的index.js   copy到我的项目文件中执行，调用了开始定位方法，却没有任何定位信息返回，console里面也没有。

![image](https://user-images.githubusercontent.com/5880204/44257492-c1544e80-a23e-11e8-8b53-6f1a31e2bc22.png)

开发环境：
    Android 8.0.0 
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-amap-geolocation": "^0.3.1"

**Comment by jialongsu** [comment]
解决了吗，同学，我也遇到这个问题了，能否分享一下解决方案？

**Comment by qiuxiang** [comment]
@lytian 试过 example？
@1035901787 根据你在其他 issue 的描述，根本就不是这个问题。

**Comment by lytian** [comment]
@qiuxiang  不知道为什么，重新init一个项目就可以了。打扰了

**Comment by afresh** [comment]
我也遇到了相同的问题，为什么呢？
`Geolocation.addLocationListener(location =>
      this.updateLocationState(location)
    )`
location一直没有返回，也就是这个监听事件没生效？

**Comment by afresh** [comment]
知道了，原来是高德开放平台没配置好。

**Comment by tvrc1990** [comment]
我也遇到相同的问题，android 上addLocationListener没有任何返回也没有出现任何错误提示，debugger 了下android源码发现toReadableMap方法上的location参数都是有定位数据的

**Comment by miqiaoli** [comment]
我也不可以，下载的example.apk倒是可以，clone你的项目，yarn run-android就不行，我自己的项目copy 你的index.js，配置了我自己的key也不行，是无法进入addLocationListener这个函数，我的keystore是按RN官方生成的 @afresh 你是什么东西没配置好？

**Comment by qiuxiang** [comment]
请自行检查权限分配的情况，最新提交的代码安装好后是不能定位成功的，因为用了较新的 api level，申请权限的写法之后补上。

example.apk 的 target 是 api level 22，系统为了向下兼容会默认授权。

**Comment by afresh** [comment]
> 我也不可以，下载的example.apk倒是可以，clone你的项目，yarn run-android就不行，我自己的项目copy 你的index.js，配置了我自己的key也不行，是无法进入addLocationListener这个函数，我的keystore是按RN官方生成的 @afresh 你是什么东西没配置好？

包名签名之类的吧。好长时间了，忘记了。

**Comment by wuhong5478** [comment]
> 请自行检查权限分配的情况，最新提交的代码安装好后是不能定位成功的，因为用了较新的 api level，申请权限的写法之后补上。
> 
> example.apk 的 target 是 api level 22，系统为了向下兼容会默认授权。

你好，申请权限的写法可以教一下吗

**Comment by qiuxiang** [comment]
@wuhong5478 https://facebook.github.io/react-native/docs/permissionsandroid

**Comment by wuhong5478** [comment]
> @wuhong5478 https://facebook.github.io/react-native/docs/permissionsandroid

谢谢大佬
