### ISSUE TITLE
ios无法获取城市信息，运行example也没有城市信息

### ISSUE THREAD

**Issue by jialongsu** [qiuxiang/react-native-amap-geolocation#19]
以下是运行example截图：
![1534770440393](https://user-images.githubusercontent.com/17847087/44342609-29649800-a4be-11e8-82af-bb492e200788.jpg)
![1534770951368](https://user-images.githubusercontent.com/17847087/44342637-3c776800-a4be-11e8-93fb-c34ee97fb7ef.jpg)

**Comment by qiuxiang** [comment]
国外坐标不支持

**Comment by qiuxiang** [comment]
Duplicate of #17

**Comment by inkCrazy** [comment]
问题我发现了，并且已经给出答复了，https://github.com/qiuxiang/react-native-amap-geolocation/issues/17
