### ISSUE TITLE
ios 编译报错

### ISSUE THREAD

**Issue by wangkai63** [qiuxiang/react-native-amap-geolocation#2]
大牛好：
iOS 按照你的安装文档进行安装后，编译报下面的错，iOS小白一枚，能否指点一下？
另位您的Podfile 中有一处错误(我的react 版本 0.50.0 最新的没有验证)
应为 pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'吧，谢谢！！

ld: warning: directory not found for option '-L/Users/wang/Library/Developer/Xcode/DerivedData/IBCSSSMOBILE-ctehwpmuzypsbtccxtylhmrcolsj/Build/Products/Debug-iphonesimulator/DoubleConversion'
ld: warning: directory not found for option '-L/Users/wang/Library/Developer/Xcode/DerivedData/IBCSSSMOBILE-ctehwpmuzypsbtccxtylhmrcolsj/Build/Products/Debug-iphonesimulator/Folly'
ld: warning: directory not found for option '-L/Users/wang/Library/Developer/Xcode/DerivedData/IBCSSSMOBILE-ctehwpmuzypsbtccxtylhmrcolsj/Build/Products/Debug-iphonesimulator/GLog'
ld: warning: directory not found for option '-L/Users/wang/Library/Developer/Xcode/DerivedData/IBCSSSMOBILE-ctehwpmuzypsbtccxtylhmrcolsj/Build/Products/Debug-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/wang/Library/Developer/Xcode/DerivedData/IBCSSSMOBILE-ctehwpmuzypsbtccxtylhmrcolsj/Build/Products/Debug-iphonesimulator/react-native-amap-geolocation'
ld: warning: directory not found for option '-L/Users/wang/Library/Developer/Xcode/DerivedData/IBCSSSMOBILE-ctehwpmuzypsbtccxtylhmrcolsj/Build/Products/Debug-iphonesimulator/yoga'
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by davidjonse** [comment]
在Libraries里添加Pods.xcodeproj即可
![image](https://user-images.githubusercontent.com/31202918/46123376-b387e500-c250-11e8-9f60-c560c39006d3.png)
