### ISSUE TITLE
react-native-amap-geolocation需要科学上网才能正常定位？？

### ISSUE THREAD

**Issue by jogxag** [qiuxiang/react-native-amap-geolocation#20]
我在开发使用react-native-amap-geolocation的时候，只要关掉VPN，手机就不能使用定位功能了，是怎么回事呢？？

**Comment by qiuxiang** [comment]
显然不是

**Comment by jogxag** [comment]
我用的时候如果不开vpn就用不起

发自我的 iPhone

**Comment by YH390389859** [comment]
react-native:0.57
使用同样在没有打开vpn的状态下无法定位,
打开vpn后就可以定位

**Comment by YH390389859** [comment]
测试了一下,在没有开启vpn的状态下addLocationListener方法也没进去

**Comment by YH390389859** [comment]
解决了,我的工位gps定位不到..开了vpn以后估计是通过网络辅助定位才定位到了的
