### ISSUE TITLE
非debug模式安卓无法定位， 开启debug立即响应定位成功

### ISSUE THREAD

**Issue by toringo** [qiuxiang/react-native-amap-geolocation#22]
```
android: 7.1.1
"react-native": "^0.55.1",
"react-native-amap-geolocation": "^0.3.2",
```
开发模式下， 开启debug定位没问题， 不开debug完全没有反应，
打包后安装也没有任何反应， 
代码copy至example：如下
![image](https://user-images.githubusercontent.com/17404085/45662216-960d9980-bb33-11e8-9ae4-af905e066de8.png)

**Comment by toringo** [comment]
@qiuxiang 该如何解决？

**Comment by qiuxiang** [comment]
你说的开 debug 指的是什么

**Comment by toringo** [comment]
> 你说的开 debug 指的是什么

连接真机，摇一摇之后选择“Debug JS Remotely”

**Comment by toringo** [comment]
问题已经解决， 配置问题，具体：
高德地图添加应用的时候获取应用的SHA1填写城开发模式的， 所以打包后无法定位。
所以生产打包和开发模式打包的应用的SHA1不一样， 需要注意。
