### ISSUE TITLE
MainApplication.java:6: 错误: 程序包cn.qiuxiang.react.geolocation不存在， 请问这里应该怎么处理

### ISSUE THREAD

**Issue by samlinWORLD** [qiuxiang/react-native-amap-geolocation#24]
E:\LianjiangProject\GongJiang\android\app\src\main\java\com\gongjiang\MainApplication.java:6: 错误: 程序包cn.qiuxiang.react.geolocation不存在
import cn.qiuxiang.react.geolocation.AMapGeolocationPackage;
^
E:\LianjiangProject\GongJiang\android\app\src\main\java\com\gongjiang\MainApplication.java:28: 错误: 找不到符号
new AMapGeolocationPackage(), 
^
符号: 类 AMapGeolocationPackage
2 个错误 
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 31.141 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by qiuxiang** [comment]
没有 link，没有编译进去

**Comment by samlinWORLD** [comment]
但我运行过react-native link react-native-amap-geolocation命令了

**Comment by qiuxiang** [comment]
你的版本 rn 版本是？

**Comment by qiuxiang** [comment]
link有没有成功 要看你的 gradle 配置

**Comment by qiuxiang** [comment]
link 可能不起作用，建议在新建项目测试

**Comment by samlinWORLD** [comment]
谢谢大佬回复，手动添加了

**Comment by lhy58** [comment]
怎么手动添加的
