### ISSUE TITLE
室内定位功能

### ISSUE THREAD

**Issue by NinjaXY** [qiuxiang/react-native-amap-geolocation#25]
具备室内定位接口吗，获取building id，和楼层

**Comment by qiuxiang** [comment]
SDK 似乎没有提到 室内定位

**Comment by NinjaXY** [comment]
> SDK 似乎没有提到 室内定位

非常感谢回复。

室内定位是有的，似乎是在另一个SDK里。https://lbs.amap.com/api/ios-indoorlocation-sdk/guide/get-location/indoorloaction

如果能加入react native就太好了。
