### ISSUE TITLE
配置了 (android/app/build.gradle)定位没反应

### ISSUE THREAD

**Issue by samlinWORLD** [qiuxiang/react-native-amap-geolocation#27]
用了一个组件react-native-image-crop-picker，需要配置如下，但是这样定位就没反应了，请问一下能有方法解决吗
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    ...
    
    defaultConfig {
      ...
      targetSdkVersion 27
      ...
    }
    ...
}

**Comment by qiuxiang** [comment]
定位没反应和 gradle 配置有什么关系

**Comment by samlinWORLD** [comment]
首先非常感谢大佬回复，因为要用到react-native-image-crop-picker这个组件，所以修改了build.gradlew，就在刚才我也把你的demo拉下来运行了一遍，如果不修改build.gradlew是没问题的，修改后点击‘开始定位’按钮没任何反应，具体什么原因我也不清楚，这是我遇到的情况，再次感谢大佬回复

**Comment by qiuxiang** [comment]
可能造成的影响是，修改了签名方式，导致 key 匹配失败；或者可能的，target 版本导致的权限兼容问题。

**Comment by samlinWORLD** [comment]
谢谢大佬，我估计是跟sdk有关，请问有没有办法可以解决这种问题
