### ISSUE TITLE
为什么打包之后就无法定位了？

### ISSUE THREAD

**Issue by aspire-t** [qiuxiang/react-native-amap-geolocation#28]
我在调试的时候可以定位，但是我用android studio打包之后，就不能定位了。请问这是什么问题

**Comment by qiuxiang** [comment]
检查 key，开发和发布的配置不一样

**Comment by aspire-t** [comment]
> 检查 key，开发和发布的配置不一样

请问下怎么配置？我在文档里没有看到相关的信息啊

**Comment by qiuxiang** [comment]
![](https://a.amap.com/lbs/static/img/2017dev_android_key.png)

发布和调试的 keystore 是不一样的
