### ISSUE TITLE
[!] No podspec found for `react-native-amap-geolocation` in `../lib/ios

### ISSUE THREAD

**Issue by samlinWORLD** [qiuxiang/react-native-amap-geolocation#29]
[!] No podspec found for `react-native-amap-geolocation` in `../lib/ios
pod install后报错，请问应该怎么处理

**Comment by YLBen** [comment]
同问

**Comment by passion0213** [comment]
I meet same issue.
Please send me solution method.

**Comment by wxingheng** [comment]
I meet same issue.
Please send me solution method.

**Comment by wxingheng** [comment]
# pod 'react-native-amap-geolocation', :path => '../node_modules/react-native-amap-geolocation'

replace bottom

  pod 'react-native-amap-geolocation', path: '../node_modules/react-native-amap-geolocation/lib/ios'

**Comment by wxingheng** [comment]
![image](https://user-images.githubusercontent.com/20256886/83738785-52502000-a687-11ea-95f7-2b4f2c26aabd.png)
