### ISSUE TITLE
逆地理编码

### ISSUE THREAD

**Issue by qiuxiang** [qiuxiang/react-native-amap-geolocation#3]

**Comment by feige-2011** [comment]
逆地理编码不起作用,不知道哪里的问题

**Comment by Yieron** [comment]
iOS确实第一次永远获不到逆地理编码，而且设置setLocatingWithReGeocode(true);后，使用Geolocation.getCurrentPosition也获取不到逆地理编码，偶尔不知道什么时候获取到了，调用Geolocation.getCurrentPosition这个方法会返回两次，调用watch会返回三次
