### ISSUE TITLE
因为后台持续定位问题，苹果审核无法通过

### ISSUE THREAD

**Issue by qiupo** [qiuxiang/react-native-amap-geolocation#31]
使用了background: number这个属性之后，在模拟器上可以在后台定位，获取信息，但是提交商城时一直说我的app使用了后台持续定位的权限，但是在APP中没有用到，总是无法过审，我把background去掉之后，删除定位权限已经通过审核了。求解怎么解决啊？项目需要这个功能啊

**Comment by qiuxiang** [comment]
没明白，background 定位的功能是开发者来可以决定是否使用的，难道不是因为不合理的使用才被拒的？
