### ISSUE TITLE
ios定位页面报错

### ISSUE THREAD

**Issue by toringo** [qiuxiang/react-native-amap-geolocation#32]
Geolocation 配置如下：
![image](https://user-images.githubusercontent.com/17404085/48672833-cdb9b180-eb75-11e8-89fe-0ea8113752aa.png)
当进入页面后报如下错误：
![image](https://user-images.githubusercontent.com/17404085/48672816-abc02f00-eb75-11e8-987b-0042f76e8839.png)

如何解决？

**Comment by qiuxiang** [comment]
没看出来，如果是 example 呢

**Comment by cuiken** [comment]
设置CLLocationManager的allowsBackgroundLocationUpdates为YES

然后打开Xcode -> Targets -> Capabilities 中的Background Modes并勾选其中的Location updates选项

以上步骤也可以通过以下配置.plist文件的方式实现 :


链接：https://www.jianshu.com/p/87bb0b8df1e7

**Comment by toringo** [comment]
> 设置CLLocationManager的allowsBackgroundLocationUpdates为YES
> 
> 然后打开Xcode -> Targets -> Capabilities 中的Background Modes并勾选其中的Location updates选项
> 
> 以上步骤也可以通过以下配置.plist文件的方式实现 :
> 
> 链接：https://www.jianshu.com/p/87bb0b8df1e7
-----------

勾选之后APP store 审核无法通通，如图
![image](https://user-images.githubusercontent.com/17404085/49280568-7e547900-f4c5-11e8-8193-7d93cd913ef2.png)

**Comment by qiuxiang** [comment]
Apple 的意思很明确，如果你的 app 没有一定要用到持续定位，那就不要用。

**Comment by qiuxiang** [comment]
duplicate of #31

**Comment by toringo** [comment]
> Apple 的意思很明确，如果你的 app 没有一定要用到持续定位，那就不要用。

---------
去掉这个属性：
![image](https://user-images.githubusercontent.com/17404085/49322680-8d323e80-f54c-11e8-9622-aff06fdcb052.png)

又会出现如下错误：
https://user-images.githubusercontent.com/17404085/48672816-abc02f00-eb75-11e8-987b-0042f76e8839.png

**Comment by qiuxiang** [comment]
就不要用 background：true

**Comment by cuiken** [comment]
没申请定位权限吧？我提交审核没问题啊。

**Comment by toringo** [comment]
> 没申请定位权限吧？我提交审核没问题啊。

---------

对， 没有加`NSLocationAlwaysAndWhenInUseUsageDescription`;

参考链接： https://stackoverflow.com/questions/32000531/nsinternalinconsistencyexception-invalid-parameter-not-satisfying-stayup

**Comment by toringo** [comment]
问题由来了，审核不通过， 英文持续定位问题，
![image](https://user-images.githubusercontent.com/17404085/49492379-fd192f80-f892-11e8-8afe-e426581558fd.png)
 但事实上我并不需要持续定位， 只需一次定位就可以， 那如何关闭持续定位？

**Comment by cuiken** [comment]
@toringo 那你只要用NSLocationWhenInUseUsageDescription就可以了，附带上描述。比如
`	<key>NSLocationWhenInUseUsageDescription</key>
	<string>若不允许，你将无法在创建电站时获取准确的位置信息</string>`
但是最好能有用户界面表示出定位的使用，而不是仅仅后台偷偷的定位然后上传。这样不太好通过

**Comment by toringo** [comment]
> @toringo 那你只要用NSLocationWhenInUseUsageDescription就可以了，附带上描述。比如
> `	<key>NSLocationWhenInUseUsageDescription</key> <string>若不允许，你将无法在创建电站时获取准确的位置信息</string>`
> 但是最好能有用户界面表示出定位的使用，而不是仅仅后台偷偷的定位然后上传。这样不太好通过

---
这个我一直是有的， 
![image](https://user-images.githubusercontent.com/17404085/49558739-17ace080-f947-11e8-8d57-641c8ccdda45.png)

**Comment by xzgilhm** [comment]
> > @toringo 那你只要用NSLocationWhenInUseUsageDescription就可以了，附带上描述。比如
> > `	<key>NSLocationWhenInUseUsageDescription</key> <string>若不允许，你将无法在创建电站时获取准确的位置信息</string>`
> > 但是最好能有用户界面表示出定位的使用，而不是仅仅后台偷偷的定位然后上传。这样不太好通过
> 
> 这个我一直是有的，
> ![image](https://user-images.githubusercontent.com/17404085/49558739-17ace080-f947-11e8-8d57-641c8ccdda45.png)
@toringo 请问您最后怎么解决问题的?
