### ISSUE TITLE
调用init报错：TypeError: undefined is not an object (evaluating 'AMapGeolocation.init')

### ISSUE THREAD

**Issue by ModyQyW** [qiuxiang/react-native-amap-geolocation#33]
项目基于GeekyAnts的[react-native-boilerplate-mobx-flow](https://github.com/GeekyAnts/react-native-boilerplate-mobx-flow)，修改过package.json，部分package.json如下所示。

_...
"dependencies": {
  "expo": "^30.0.0",
  "lodash": "4.17.4",
  "mobx": "3.4.1",
  "mobx-react": "4.3.5",
  "native-base": "2.6.1",
  "query-string": "^6.0.0",
  "react": "16.3.1",
  "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
  "react-native-amap-geolocation": "^0.3.2",
  "react-native-datepicker": "^1.7.2",
  "react-navigation": "^2.13.0"
}
..._

项目使用`npm i react-native-amap-geolocation`安装后，重新`npm install`，运行时控制台报错`[TypeError: undefined is not an object (evaluating 'AMapGeolocation.init')]`。部分代码如下所示。

_...
import { Geolocation } from "react-native-amap-geolocation"
...
let { status } = await Permissions.askAsync(Permissions.LOCATION);
if (status !== 'granted') {
  Toast.show({
    text: "请打开位置信息",
    duration: 1500,
    position: "top",
    textStyle: { textAlign: "center" },
    type: 'danger'
  });
}
await Geolocation.init({
  ios: iosKey,
  android: androidKey,
});_

请问该如何解决？
如需更多信息，请指出。

**Comment by qiuxiang** [comment]
使用这个库是要编译的

**Comment by KenSuperboy** [comment]
我想出现了这个问题，你说的编译是什么意思

**Comment by xjy0925** [comment]
react-native link react-native-amap-geolocation
 参照 使用文档 手动那部分: https://qiuxiang.github.io/react-native-amap-geolocation/#/
