### ISSUE TITLE
如何获取移动方向 direction？

### ISSUE THREAD

**Issue by superlehehe** [qiuxiang/react-native-amap-geolocation#37]
文档中没有介绍，我在使用是经纬度，速度，位置等信息都能获取，但没有获取到设备的移动方向direction。请问要如何解决？

**Comment by qiuxiang** [comment]
Android 貌似忘了写了。。

**Comment by superlehehe** [comment]
能不能加上此功能，这样功能就比较完整了。

**Comment by superlehehe** [comment]
楼组给出如何手工调整代码，增加direction的说明也行。

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap-geolocation/blob/master/lib/android/src/main/java/cn/qiuxiang/react/geolocation/AMapGeolocationModule.java

需要改这个文件，再返回的数据里增加。

**Comment by superlehehe** [comment]
AMapGeolocationModule.java 文件里90行处加入一行：
map.putDouble("direction", location.getBearing());

经测试可行
感谢楼主的回复！

**Comment by MickeyMouse623** [comment]
![image](https://user-images.githubusercontent.com/18524460/60868309-55684380-a25f-11e9-8252-25ae17752404.png)

增加 ```map.putDouble("direction", location.getBearing());``` 这样获取的值和 ```heading``` 不是一样的吗。我用 ```location.getDirection``` 报错，错误信息是：

![image](https://user-images.githubusercontent.com/18524460/60868458-a7a96480-a25f-11e9-900a-62f71b385474.png)
