### ISSUE TITLE
希望能有IOS能通过link 实现

### ISSUE THREAD

**Issue by meiqi1992** [qiuxiang/react-native-amap-geolocation#38]
希望能有IOS能通过link 实现， 因为很多没做过ios的对pod不会用，并且pod出现的问题也不知道如何解决。如果能直接link关联使用

**Comment by qiuxiang** [comment]
我当然也希望 link 就可以，但这个高德地图定位 SDK 依赖一些东西，link 帮不上忙，link 只是把代码 link，有很多设置仍然要开发者自己设置。
