### ISSUE TITLE
debug中显示:Cannot read property 'init' of undefined,

### ISSUE THREAD

**Issue by FaceOnFace** [qiuxiang/react-native-amap-geolocation#39]

**Comment by MonkeyInWind0** [comment]
![image](https://user-images.githubusercontent.com/34543887/50822813-8f6a9280-136d-11e9-89b3-c6975e57314e.png)
NativeModules里没有AMapGeolocation

**Comment by MonkeyInWind0** [comment]
找到问题在这里  但是还没整明白怎么解决

**Comment by qiuxiang** [comment]
那就是没有把这个项目编译进去

**Comment by MonkeyInWind** [comment]
> 那就是没有把这个项目编译进去

怎么编译进去  npm install之后按文档调用的  还需要其他操作吗

**Comment by qiuxiang** [comment]
原生组件只是 install 肯定还不行呀，你没有按照安装文档进行配置吗

**Comment by MonkeyInWind0** [comment]
> 原生组件只是 install 肯定还不行呀，你没有按照安装文档进行配置吗

之前没配置  我自己的问题。。。
配置之后ios可以定位  android没反应  这个可能是什么原因  sdk我用的27   不知道和这个有没有关系

**Comment by github123333** [comment]
大佬有没有找到解决方法，被困好久没解决了，求解决大佬
