### ISSUE TITLE
更新版本后,获取数据中还是没有地址信息

### ISSUE THREAD

**Issue by feige-2011** [qiuxiang/react-native-amap-geolocation#4]

**Comment by qiuxiang** [comment]
别只是抛出问题，你要提供信息啊。

android？ios？当前定位到了哪？试过 example 了？

**Comment by feige-2011** [comment]
ios     
 "react": "16.0.0-beta.5",
   "react-native": "0.49.5"
试过运行 ios 的 demo, 没有返回逆地址信息,  在 Pods 文件中检测,只返回了 Loation 信息

**Comment by qiuxiang** [comment]
基本可以肯定是 key 的问题：

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1709072/39632546-f5abb14a-4fe7-11e8-8559-049dabd4d613.png">

用自己的 key 试试。

**Comment by qiuxiang** [comment]
基本可以确定与 #17 是同一个问题
