### ISSUE TITLE
希望有单次定位返回Promise的api

### ISSUE THREAD

**Issue by M45ter** [qiuxiang/react-native-amap-geolocation#42]
hi，感谢作者封装了高德SDK方便RN开发者！
业务中需要单次定位返回结果，同一个界面可能有多处使用，目前的方式，listener中无法明确知道是哪个业务的数据接着执行什么，而且多个page都有监听的话，多个listener应该都会有数据，所以感觉还是有一个单次定位返回Promise的api使用起来会比较方便，刚接触RN，希望描述能看懂

**Comment by qiuxiang** [comment]
之前是觉得 Android 版单次定位不好实现，因为和连续定位共用使用同一个 listener，不过现在想想，只要另起一个 client 就没问题了，之后考虑实现。

不过即便没有单次定位也没什么问题，如果你用 redux，mobx 这些状态管理的话。

**Comment by M45ter** [comment]
> 之前是觉得 Android 版单次定位不好实现，因为和连续定位共用使用同一个 listener，不过现在想想，只要另起一个 client 就没问题了，之后考虑实现。
> 
> 不过即便没有单次定位也没什么问题，如果你用 redux，mobx 这些状态管理的话。

之前做原生的，前端的知识刚接触，还未用过状态管理；是的，android原生单次定位都是new一个client，一个监听listener

**Comment by krmao** [comment]
模糊定位无法连续定位，现在必须要单次定位了
