### ISSUE TITLE
在比较偏僻的地方定位会导致闪退，提示"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[8]'"

### ISSUE THREAD

**Issue by jialongsu** [qiuxiang/react-native-amap-geolocation#48]
环境：
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-amap-geolocation": "^0.3.2",

开发工具：Mac

定位的经纬度：lat: 38.6511983323, long: 82.3974609375

错误提示：
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[8]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108b921bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000109cab735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108ade4ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000108c01541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x0000000108b8dc9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   yidaoClient                         0x000000010466be4f -[RCTLocationModule json:reGeocode:] + 1839
	6   yidaoClient                         0x000000010466c4b1 -[RCTLocationModule amapLocationManager:didUpdateLocation:reGeocode:] + 129
	7   yidaoClient                         0x00000001046c9f34 __72-[AMapLocationManager notifySerialLocateDelegateWithLocation:reGeocode:]_block_invoke + 93
	8   libdispatch.dylib                   0x000000010bf64595 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000010bf65602 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010bf7299a _dispatch_main_queue_callback_4CF + 1541
	11  CoreFoundation                      0x0000000108af73e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x0000000108af1a76 __CFRunLoopRun + 2342
	13  CoreFoundation                      0x0000000108af0e11 CFRunLoopRunSpecific + 625
	14  GraphicsServices                    0x000000010f62c1dd GSEventRunModal + 62
	15  UIKitCore                           0x00000001139a781d UIApplicationMain + 140
	16  yidaoClient                         0x00000001043f6d00 main + 112
	17  libdyld.dylib                       0x000000010bfdb575 start + 1
	18  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jialongsu** [comment]
好像是reGeocode对象里面的有些字段在这个经纬度的时候为null，然后导致闪退。我现在加了一个值的判断是没有闪退了，但是监听不到数据的返回
![image](https://user-images.githubusercontent.com/17847087/52778956-22d86700-3082-11e9-8051-3e0e291742fb.png)

**Comment by subenkun** [comment]
我也在山沟沟里面定位时碰到类似问题

**Comment by inkCrazy** [comment]
我也遇到了这个问题，我模拟定位，有些地区不能完整获取reGeocode里面的关键字，然后导致的闪退。经纬度：（31.264654，121.505133）获取定位之后逆地理信息获取的坐标信息，没有逆地理的坐标位置json：{ speed: -1,
  latitude: 31.26263481987847,
  altitude: 0,
  longitude: 121.50954833984375,
  accuracy: 5,
  direction: -1,
  timestamp: 1555564588475.291 }
多次定位之后有逆地理信息之后的结果：（最后按照楼上@1035901787的方式修改之后的结果）
{ speed: -1,
  timestamp: 1555564588475.291,
  address: '上海市杨浦区靠近众和新苑',
  longitude: 121.50954833984375,
  streetNumber: '',
  adCode: '310110',
  country: '中国',
  province: '上海市',
  poiName: '众和新苑',
  latitude: 31.26263481987847,
  altitude: 0,
  street: '',
  cityCode: '021',
  city: '上海市',
  district: '杨浦区',
  accuracy: 5,
  direction: -1 }
可以看出streetNumber和street字段有些区域会有null的情况
