### ISSUE TITLE
逆地址编码不成功

### ISSUE THREAD

**Issue by feige-2011** [qiuxiang/react-native-amap-geolocation#5]
ios 项目 ,
定位信息中没有逆地理编码,但是当我调用过 react-Native-amap3D 地图之后,再去定位,就都有城市信息就都有了

**Comment by qiuxiang** [comment]
你得先确认是不是 key 的问题 https://github.com/qiuxiang/react-native-amap-geolocation/issues/4#issuecomment-386614538

**Comment by feige-2011** [comment]
应该不是 key 的问题,因为我在你的代码基础上把连续定位,改成了单次定位,就返回逆地理编码了

**Comment by qiuxiang** [comment]
哪里有单次定位，`getLastLocation`？

**Comment by qiuxiang** [comment]
是不是 key 的问题，你要自己去看 log，而不是靠直觉

**Comment by feige-2011** [comment]
我是看的高德地图的开发文档,有单次定位, log 我不是特别会看,我在改成单次定位时,并没有改变传入 key 的写法,所以不是key 的问题

调用 AMapLocationManager 的 requestLocationWithReGeocode:completionBlock: 方法，请求一次定位。

// 带逆地理（返回坐标和地址信息）。将下面代码中的 YES 改成 NO ，则不会返回地址信息。
[self.locationManager requestLocationWithReGeocode:YES completionBlock:^(CLLocation *location, AMapLocationReGeocode *regeocode, NSError *error) {
        
        if (error)
        {
            NSLog(@"locError:{%ld - %@};", (long)error.code, error.localizedDescription);
            
            if (error.code == AMapLocationErrorLocateFailed)
            {
                return;
            }
        }
        
        NSLog(@"location:%@", location);
        
        if (regeocode)
        {
            NSLog(@"reGeocode:%@", regeocode);
        }
    }];

**Comment by qiuxiang** [comment]
你还是先确认 key 的问题吧，我是确认过如果 key 不正确是得不到逆地理编码的，而 key 正常的情况下，真机可以正常得到地址。

即便如你所说单次定位不需要 key 也能获取到逆地理编码，我也不会因此把连续定位改成单次的实现。

**Comment by feige-2011** [comment]
单次定位也是需要 key 的,key我没有改,我能得到逆地理编码,说明key 是没问题的, 应该是其他的问题吧

**Comment by qiuxiang** [comment]
可是如果你连自己的 key 是不是正确都不能确认的话，又怎么确认单次定位不需要（或者需要） key 也能返回逆地理编码？

**Comment by feige-2011** [comment]
高德地图文档中有写, 单次定位肯定是需要 key 的

**Comment by feige-2011** [comment]
我返回逆地理编码,肯定key,是正确的

**Comment by qiuxiang** [comment]
哪个文档？

**Comment by qiuxiang** [comment]
单次定位确实需要 key 才能得到地址，但你说的在连续定位里无法获取到地址，没法重现，我也不认为目前的代码有什么问题，在有助于这个问题推进、确认的信息出现之前，我不再评论。

**Comment by qiuxiang** [comment]
另外，这个问题已经重复了，故关掉。

**Comment by fgxls** [comment]
我的key确认是正确的 就是没有中文描述 只有经纬度

**Comment by inkCrazy** [comment]
问题我发现了，并且已经给出答复了，https://github.com/qiuxiang/react-native-amap-geolocation/issues/17
