### ISSUE TITLE
为什么会回调多次

### ISSUE THREAD

**Issue by JonsonHI** [qiuxiang/react-native-amap-geolocation#52]
发现Geolocation.addLocationListener(location => {
    console.log(location);
}

会回调多次

能只调用一次吗

**Comment by qiuxiang** [comment]
只调用一次，那就在接收到定位的时候 `stop` 就可以了

**Comment by JonsonHI** [comment]
我当前是这么写的
再程序启动的时候 就使用定位 然后赋值给需要用到的地方  回调之后进行stop操作
```
Geolocation.start()
        await Geolocation.addLocationListener(location => {
            HomeStore.latitude = location.latitude
            HomeStore.longitude = location.longitude
            HomeStore.latitudeFirst = location.latitude
            HomeStore.longitudeFirst = location.longitude
            HomeStore.upMapDateList((array) => {
                Geolocation.stop()
            }, () => {
            })

        })
```

然后再其他地方使用这个Geolocation.start()的时候
还是连续的调用了3次 才停止

**Comment by qiuxiang** [comment]
因为所有接口的调用都是异步的，stop 的期间，定位结果可能已经数次到达

**Comment by winterwd** [comment]
看了 iOS 的源码，@qiuxiang 是用了 `startUpdatingLocation` 这个是 「持续定位」，所以会有多次回调，如果要用单次定位的话，请使用这个 `requestLocationWithReGeocode:completionBlock: `

参考高德官方开发指南：[singlelocation](https://lbs.amap.com/api/ios-location-sdk/guide/get-location/singlelocation)

**Comment by qiuxiang** [comment]
问题在于，android 没有提供单次定位的单独接口，为了一致性，就只提供了连续定位。

最近我在重构这个项目，就不再追求接口的一致性，而尽可能地提供原生接口。

**Comment by winterwd** [comment]
为了保证接口统一性，可以在 Android 中 添加一个相同的方法:
```
@ReactMethod
public void startSingle() {
    locationClient.startLocation();
}
```

**Comment by qiuxiang** [comment]
但这两个接口的行为是完全不一样的，ios 是单次回调，而 android 是 listener

**Comment by winterwd** [comment]
iOS 单次定位这样处理，就可以了

```
// 单次定位
RCT_EXPORT_METHOD(startSingle) {
    [_manager requestLocationWithReGeocode:YES completionBlock:^(CLLocation *location, AMapLocationReGeocode *regeocode, NSError *error) {
        [self amapLocationManager:nil didUpdateLocation:location reGeocode:regeocode];
    }];
}
```
最后回调结果还是通过 `listener`。

另外我发现， `Geolocation` 只有 `addLocationListener`，没有 `remove`，建议加一个 `removeLocationListener`

**Comment by qiuxiang** [comment]
不需要再多一个 remove 接口，因为 addLocationListener 返回的是 Subscription
```javascript
const listener = addLocationListener()
listener.remove()
```

**Comment by winterwd** [comment]
😳 不好意思，看差行了 `() => void`

**Comment by JonsonHI** [comment]
我修改了下安卓和ios的代码 不知道怎么放出来.
可以单次定位,还加上了权限的判断.
只是每次定位后我都调用了 stop 方法

**Comment by JonsonHI** [comment]
还有就是安卓初次定位很慢的问题 我一直没解决掉,不知道是回调问题
还是高德本身就有问题

**Comment by JonsonHI** [comment]
https://www.jianshu.com/p/6f4f0674901a 
这是我的简书地址,和修改后的代码.
加了 第三方导航跳转 和  单次定位,还有 定位权限是否开启的判断.
希望对大家有帮助

**Comment by TrustTheBoy** [comment]
addLocationListener在真机回调太慢了
