### ISSUE TITLE
iOS link成功未发现*.a文件，手动配置也没发现文件

### ISSUE THREAD

**Issue by Natuka** [qiuxiang/react-native-amap-geolocation#56]
RN版本 0.59.5
系统 MacOS 10.14.1
XCode 10.1

react-native-amap-geolocation 包版本 1.0

![image](https://user-images.githubusercontent.com/9472604/57211741-f5151580-7013-11e9-983a-0c32f0598c7d.png)
![image](https://user-images.githubusercontent.com/9472604/57211799-2c83c200-7014-11e9-8053-9f4ef13ab14a.png)

![image](https://user-images.githubusercontent.com/9472604/57211984-cfd4d700-7014-11e9-9931-dc425dbf0afb.png)

**Comment by qiuxiang** [comment]
在这里找并添加：
![](https://user-images.githubusercontent.com/1709072/55277356-3e4db780-533a-11e9-8f3b-141b005e449a.png)

**Comment by Natuka** [comment]
上面那个项目要单独下载？
目前我在上面的那个位置，没找到*.a文件，

**Comment by qiuxiang** [comment]
这是另一个项目的截图，我的意思是你要在 Build Phases ➜ Link Binary With Libraries 添加，或者你在这里截接一个图我看看

**Comment by Natuka** [comment]
正在重新整理项目，加入后在删除添加进的东西后，就跑不起来了。。。

**Comment by Natuka** [comment]
link之后编译报路径找不到
![image](https://user-images.githubusercontent.com/9472604/57217040-1f6ecf00-7024-11e9-8a37-73e551028547.png)

在这边引入是没问题的
![image](https://user-images.githubusercontent.com/9472604/57217060-2b5a9100-7024-11e9-9003-3cd8186640bc.png)

**Comment by Natuka** [comment]
![image](https://user-images.githubusercontent.com/9472604/57217612-aff9df00-7025-11e9-84e2-501442d029d0.png)
![image](https://user-images.githubusercontent.com/9472604/57217648-c9029000-7025-11e9-8e68-2920d9eb2277.png)

**Comment by Natuka** [comment]
![image](https://user-images.githubusercontent.com/9472604/57218448-e8022180-7027-11e9-9391-61b0aaf3083a.png)
目前把组件里面的代码复制到本地，然后在按照高德官方的demo，编译没报错了。。。
![image](https://user-images.githubusercontent.com/9472604/57218972-50053780-7029-11e9-8f05-8f3442733213.png)
把项目移动到本地了，然后出现了其他人遇到的speed == -1

**Comment by qiuxiang** [comment]
你下载 framework 放到 ios 目录了吗

**Comment by Natuka** [comment]
嗯，下载的东西有引进来
![image](https://user-images.githubusercontent.com/9472604/57221475-01a86680-7032-11e9-951d-17c8c666dcd2.png)

**Comment by qiuxiang** [comment]
我得看你的把 framework 放到哪了，我在项目设置的查找路径是 ios 目录，如果你是放到了其他目录，即便是加一层目录都会导致找不到

**Comment by Natuka** [comment]
你的意思是一定要放在ios/根目录下？

**Comment by Natuka** [comment]
![image](https://user-images.githubusercontent.com/9472604/57231949-33c7c180-704e-11e9-8973-659d782a7b9f.png)

这个是文档的说明。
因为看起来问题就是处在目录找不到，
最有可能就是上面的问题，但是不知道如何处理，也是过很多次。

**Comment by Natuka** [comment]
![image](https://user-images.githubusercontent.com/9472604/57232585-7ccc4580-704f-11e9-81ab-ca278fb9ad58.png)
@qiuxiang 按照你的意思？这个一定要在ios跟目录下？

**Comment by qiuxiang** [comment]
是的，一定要在 ios 目录下

**Comment by qiuxiang** [comment]
不然你得改 AMapGeolocation.xcodeproj 里的 search path

**Comment by Natuka** [comment]
已经处理，然后现在出现另外一个问题，就是无法一直定位。
