### ISSUE TITLE
geolocation.ts 111行代码

### ISSUE THREAD

**Issue by subenkun** [qiuxiang/react-native-amap-geolocation#57]
function toPosition(location: Location) {
  return {
    location,
    coords: {
      latitude: location.latitude,
      longitude: location.longitude,
      altitude: location.altitude,
      accuracy: location.accuracy,
      altitudeAccuracy: null, // 高德定位接口没有找到对应的数据
      heading: location.heading,
      speed: location.speed
    },
    timestamp: location.timestamp
  };
}
假如location为null，coords会报错，直接返回location更合适吧

**Comment by qiuxiang** [comment]
嗯，这个得处理下，返回 coords 是为了兼容 web 标准接口

**Comment by qiuxiang** [comment]
不过原生代码那里不可能返回 null，如果你有遇到返回 null 的情况，还望说明下

**Comment by subenkun** [comment]
嗯，目前没碰到过，只是觉得同时返回location和location有点奇怪

**Comment by qiuxiang** [comment]
location 是多返回的并不属于 geolocation api 的一部分

**Comment by subenkun** [comment]
好的。了解
