### ISSUE TITLE
_1.addLocationListener is not a function

### ISSUE THREAD

**Issue by wangdanting** [qiuxiang/react-native-amap-geolocation#60]
![A1373D9E-A2A3-489B-A60D-23C5B30B35F1](https://user-images.githubusercontent.com/16220538/57284130-24df1e80-70e3-11e9-9a0c-8b0f2ecbc363.png)
![4B9ED927-405C-400D-908E-5A2BDEB9FAE0](https://user-images.githubusercontent.com/16220538/57284139-29a3d280-70e3-11e9-8eee-55804f032552.png)

**Comment by chj-damon** [comment]
@qiuxiang 为什么关掉？现在还是有这个报错
