### ISSUE TITLE
ios init失败大概有哪些可能性

### ISSUE THREAD

**Issue by Wodezhishi321** [qiuxiang/react-native-amap-geolocation#63]

**Comment by Wodezhishi321** [comment]
如题，是不是ios key没配置好的缘故？

**Comment by qiuxiang** [comment]
怎么失败？

**Comment by Wodezhishi321** [comment]
显示Possible Unhandled Promise Rejection(id:0)...后面显示reactNativeAmapGeolocation.init啥的

**Comment by qiuxiang** [comment]
最好有截图

**Comment by Wodezhishi321** [comment]
![1f07bc1b1ffa21731dae85aa461fd54](https://user-images.githubusercontent.com/20784096/57508149-52baa200-7333-11e9-9c7f-670accdeadbc.jpg)

**Comment by qiuxiang** [comment]
init 不是在 Geolocation 对象的

**Comment by qiuxiang** [comment]
```javascript
import { init, Geolocation } from "react-native-amap-geolocation";
```

**Comment by Wodezhishi321** [comment]
我记得十几天前是0.3.2的版本吧现在变成1.0.1的版本后之前的example的用法是不能用了么

**Comment by Wodezhishi321** [comment]
你发的那段我也引入了

**Comment by qiuxiang** [comment]
1.0 之后接口做调整了，不完全兼容以前的接口，但 init、start、stop、addLocationListener 这些还是不变的

**Comment by Wodezhishi321** [comment]
![image](https://user-images.githubusercontent.com/20784096/57508664-b1345000-7334-11e9-9189-25b2ce268acd.png)

**Comment by qiuxiang** [comment]
引入是一回事，但你不能 `Geolocation.init()`，而是用引入的 `init()`，这两个是语言解释上完全不一样的

**Comment by Wodezhishi321** [comment]
你看下我是这样子的用的你现在的文档上的示例

**Comment by qiuxiang** [comment]
你看新的示例，https://github.com/qiuxiang/react-native-amap-geolocation/blob/master/index.js

**Comment by qiuxiang** [comment]
看代码应该是没问题的

**Comment by Wodezhishi321** [comment]
那是不是link没成功的可能？

**Comment by Wodezhishi321** [comment]
反正就是停在init这步了看样子是

**Comment by Wodezhishi321** [comment]
我百度到的比较像的问题是这个所以我代码里加了两个.catch但是没有效果
![image](https://user-images.githubusercontent.com/20784096/57509646-5e0fcc80-7337-11e9-8183-8b88d6cdba2c.png)

**Comment by qiuxiang** [comment]
你试试运行这个项目的 example？

**Comment by qiuxiang** [comment]
在这里的 try catch 是掩耳盗铃的做法，init 方法不存在意味着没有对应的原生方法，那么确实有可能是没有 link 成功，或 link 成功但编译有问题

**Comment by qiuxiang** [comment]
link 的问题，可以参考说明文档里的手动配置

**Comment by Wodezhishi321** [comment]
手动配置发现这一步没有做，
![image](https://user-images.githubusercontent.com/20784096/57510508-9912ff80-7339-11e9-9930-420e4ec47e4e.png)
然后加了这一行代码后编译就出错了报错

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':rongcloud-react-native-imlib' could not be found in project ':app'.

**Comment by Wodezhishi321** [comment]
是需要再安装一个这个依赖么

**Comment by qiuxiang** [comment]
。。写错了，应该是 `react-native-amap-geolocation`

**Comment by Wodezhishi321** [comment]
那我link本来就是成功的不需要手动配置然后我运行你的example发现也会报错
![fa9a3af940aaed9d2f3444301bfda38](https://user-images.githubusercontent.com/20784096/57512773-2d339580-733f-11e9-9a97-a7620be1d436.jpg)

**Comment by qiuxiang** [comment]
主要看 MainApplication.java，如果这里没有加入 AMapGeolocationPackage 的话，就不会编译进去，如果加入了这段，但其他配置有问题的话，编译也不会通过。

**Comment by qiuxiang** [comment]
运行 yarn build 了吗？

**Comment by Wodezhishi321** [comment]
没有

**Comment by Wodezhishi321** [comment]
用了之后可以了可是我自己的项目里没有yarn build这个命令

**Comment by Wodezhishi321** [comment]
问题解决了build.gradle里手动配置过后再npm install一下，之后运行就可以定位了
