### ISSUE TITLE
做安卓端实时定位发送的时候，想要停止实时定位，  启用 Geolocation.stop()方法后，怎么还是一直到发送实时定位，stop（）方法并不起作用

### ISSUE THREAD

**Issue by heimanba19924** [qiuxiang/react-native-amap-geolocation#64]
![image](https://user-images.githubusercontent.com/27919350/57506403-4da72400-732e-11e9-9a6e-9bc660f77d43.png)

**Comment by qiuxiang** [comment]
Geolocation 没有 stop 方法

**Comment by qiuxiang** [comment]
看接口文档：https://qiuxiang.github.io/react-native-amap-geolocation/api/classes/geolocation.html

**Comment by puchenhui** [comment]
请问下你在实时定位的时候，有没有遇到过用户静止状态下，定位漂移的问题
