### ISSUE TITLE
ios 定位后是无法获得adcode等相关信息么？

### ISSUE THREAD

**Issue by Wodezhishi321** [qiuxiang/react-native-amap-geolocation#65]

**Comment by qiuxiang** [comment]
iOS 要调用这个：
https://github.com/qiuxiang/react-native-amap-geolocation/blob/f4a4c2488ea7401e0469f1ef6a9f0949d961af7f/src/index.ts#L293-L301

**Comment by Wodezhishi321** [comment]
我是这样用法的返回的依旧没有adCode等信息是不是因为我这个不是连续定位？
<img width="1508" alt="WeChat120b5b1ca2bac5331aec6709aaaca9cb" src="https://user-images.githubusercontent.com/20784096/57597557-6871d680-7582-11e9-9673-9f5965c25fcd.png">

**Comment by Wodezhishi321** [comment]
解决了换用连续定位的就成功了

**Comment by qiuxiang** [comment]
你的代码里，调用其他方法在 init 之前就是不对的

**Comment by qiuxiang** [comment]
并不是 getCurrentPosition 不能返回 reGeocode
