### ISSUE TITLE
info.plist里已经配置了获取定位权限的请求，为何ios还是无法弹出获取定位权限的提示？

### ISSUE THREAD

**Issue by Wodezhishi321** [qiuxiang/react-native-amap-geolocation#67]

**Comment by Wodezhishi321** [comment]
如图
<img width="1156" alt="WeChat6af759b220e54f83852f6a3510b0e463" src="https://user-images.githubusercontent.com/20784096/57748404-650a5680-770c-11e9-9b0e-936aeda606f6.png">

**Comment by tivjoe** [comment]
对的，我也遇到了这个问题。ios上没用弹出权限的任何提示，并且console.log()不出任何的信息

**Comment by tivjoe** [comment]
解决办法：只使用NSLocationWhenInUseUsageDescription ，NSLocationAlwaysUsageDescription这两个权限，即可顺利弹出定位权限，如果需要开启后台定位权限和你一样，在init之后设置setAllowsBackgroundLocationUpdates（true），保证了在定位前开启后台定位。设置了YES的时候 Background Modes 中的 Location updates 处于选中状态。真机测试ios12,一切正常。

**Comment by Wodezhishi321** [comment]
我用你说的方法，在模拟器上是可以弹出的，但是在ios10.3系统的iphone7真机上就没有弹出

**Comment by tivjoe** [comment]
参照高德地图文档，NSLocationWhenInUseUsageDescription ，NSLocationAlwaysUsageDescription这两个权限应该是ios8-10使用的，但是奇怪的是ios11以上却没有问题，反到ios11以下出现了问题。

**Comment by qiuxiang** [comment]
具体参考 Apple 官方文档：https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysusagedescription

`NSLocationWhenInUseUsageDescription` 和 `NSLocationAlwaysAndWhenInUseUsageDescription` 是 iOS 11+ 用的，`NSLocationAlwaysUsageDescription` 才是 iOS 11 以下用

**Comment by Wodezhishi321** [comment]
我现在只留下了When in Use Usage Description的权限请求在ios10和ios12的模拟器上都是可以弹出了ios10的真机上也可以弹出提示了
