### ISSUE TITLE
计算两点间距离

### ISSUE THREAD

**Issue by taoqf** [qiuxiang/react-native-amap-geolocation#68]
能否添加这个支持呢？

Android上的文档我找到了，IOS上文档比较旧，没能够找到。

https://lbs.amap.com/api/android-location-sdk/guide/additional-func/amap-calculate-tool

calculateLineDistance

**Comment by qiuxiang** [comment]
这完全可以用其他库，比如 https://github.com/manuelbieh/Geolib

**Comment by taoqf** [comment]
多谢
