### ISSUE TITLE
ReactNative的项目，不是原生使用RN，在IOS上使用pod安装的方式，无法使用

### ISSUE THREAD

**Issue by InfoSpace** [qiuxiang/react-native-amap-geolocation#7]
编译报下面错误
'React/RCTEventEmitter.h' file not found
请问应该怎么解决。网上搜不到合适的方案。
对IOS不熟悉，请见谅

**Comment by InfoSpace** [comment]
按ios安装说明，安装最终会报283 duplicate symbols for architecture arm64
这么多重复的错误，把pod中RCTText RCTNetWork. RCTWebSocket 都注销后，就会报上面'React/RCTEventEmitter.h' file not found的错误
RN 版本 0.55

**Comment by qiuxiang** [comment]
这种编译问题没法给你帮助，自己参考 example 和 编译测试

**Comment by MirGhojam** [comment]
我也有同样的问题，为什么单独安装React。只安装定位pod不就应该可以引用到RN项目里的React吗？

**Comment by ichenwanbing** [comment]
我也是pod安装的 报同样的错误 你们解决了吗  分享一下  QQ351795515

**Comment by wxingheng** [comment]
同样的错误，大家可以分享一下吗
react-native-amap-geolocation/lib/ios/AMapGeolocation.m:3:9: fatal error: 'React/RCTEventEmitter.h' file not found
