### ISSUE TITLE
再没有授权定位的情况下定位导致app闪退

### ISSUE THREAD

**Issue by subenkun** [qiuxiang/react-native-amap-geolocation#70]
初次安装，在没有点击授权的情况下执行Geolocation.watchPosition会导致app闪退

**Comment by qiuxiang** [comment]
android？

**Comment by subenkun** [comment]
ios和Android都存在同样的问题

**Comment by qiuxiang** [comment]
我确认下

**Comment by subenkun** [comment]
如果手机上已经有该app的情况下，这个问题是重现不了的，须卸载重装。

**Comment by phpsmarter** [comment]
这个你要自己进行判断,如果授权了就获取信息, 如果没有授权,就不做什么操作,直接返回 .

如果你不做判断, 组件没有权限,但是又要执行,有的手机就会推出了.
可以参见 bbs.reactiantive.cn  中安卓权限的的用法

**Comment by subenkun** [comment]
@phpsmarter Android和IOS都会闪退

**Comment by phpsmarter** [comment]
> @phpsmarter Android和IOS都会闪退

你自己要做判断才能使用

```
let granted = await PermissionsAndroid.request(
    PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION,

    {
      title: "本应用需要使用定位权限",
      message: "需要您打开GPS,然后就可以顺利找到加油站啦!",
      buttonNeutral: "让我再想想",
      buttonNegative: "不行",
      buttonPositive: "打开GPS"
    }
  );
if (granted === PermissionsAndroid.RESULTS.GRANTED) {
    await init({
      ios: "",
      android: "you api key"
    });
    setNeedAddress(true);

    await Geolocation.getCurrentPosition(({ coords }) => {
      //console.log(coords);
      AsyncStorage.setItem("LAT", `${coords.latitude}`);
      AsyncStorage.setItem("LNG", `${coords.longitude}`);
    });
  }
```

你不做判断, 用户没有赋予定位权限, 这个包就会执行获取位置的操作, 但是又获取不到信息, 所以就报错, 在打包之后就有可能闪退.  问题不是闪退不闪退, 问题是如果用户不授权, 你怎么做. 这一步你怎么考虑?

**Comment by subenkun** [comment]
@phpsmarter 哦，或许你不明白我要表达什么，我现在说的是闪退的问题，不是用户授不授权的问题。建议你了解下程序的健壮性和鲁棒性

**Comment by qiuxiang** [comment]
@subenkun 闪退也是会有错误日志的，如果你能提供错误日志或许可以找到问题并解决，现在我还没有时间能亲自确认

**Comment by qiuxiang** [comment]
能有个堆栈信息也好

**Comment by subenkun** [comment]
![error](https://user-images.githubusercontent.com/902220/58604283-6ae46800-82c6-11e9-9324-5ee44fe321cc.png)
@qiuxiang 麻烦你看下

**Comment by qiuxiang** [comment]
那我知道了，确实是没处理好，和 #72 是一样的，等下就发个新版
