### ISSUE TITLE
一台手机能定位，另一台手机却不能定位？

### ISSUE THREAD

**Issue by whyjson** [qiuxiang/react-native-amap-geolocation#72]
**为了节省大家的时间，请尽可能详细地说明问题，并最好提供截图（特别是出错信息）。**
这个配置是一位同事在他电脑上配好的，然后我down了他的代码，在我这边的手机上就不能定位，使用的1.0.2版本报错了，换成1.0.1版本虽然没有报错，但是定位结果都是undefined
1.0.2
![图片](https://user-images.githubusercontent.com/26684053/58321997-43b71200-7e52-11e9-8d9d-d61c668dcb38.png)
1.0.1
![图片](https://user-images.githubusercontent.com/26684053/58322054-6fd29300-7e52-11e9-964f-dea9e1ff60e7.png)

**Comment by qiuxiang** [comment]
1.0.2 报什么错？

**Comment by qiuxiang** [comment]
看样子是定位出错了，最新版错误处理的问题我再确认下

**Comment by whyjson** [comment]
![image](https://user-images.githubusercontent.com/26684053/58401488-90882c00-8090-11e9-9df1-d7b57c37af8c.png)
这个是1.0.2报得错误。

**Comment by qiuxiang** [comment]
显然是触发了错误回调，但你调用的时候没有提供错误回调函数，这个错误是我这边要处理的，当使用者不打算提供错误回调时也不应该出错。但现在你要提供一个回调函数以便获取具体的错误信息。

**Comment by qiuxiang** [comment]
错误回调写在第二个参数：
```javascript
Geolocation.getCurrentPosition(({ coords }) => {
  console.log(coords);
}, error => console.error(error));
```

**Comment by whyjson** [comment]
ok了，大佬，解决了。是debug包的签名问题

**Comment by whyjson** [comment]
哦哦，收到，谢大佬。
