### ISSUE TITLE
关于 #import <AMapFoundationKit/AMapFoundationKit.h>

### ISSUE THREAD

**Issue by cskyr** [qiuxiang/react-native-amap-geolocation#74]
"react": "16.6.3",
 "react-native": "^0.57.8",

将react-native-amap3d及react-native-amap-geolocation使用cocoapods进行安装，pod install后，进行react-native run-ios，会报以下错误；请帮忙看下，怎么解决呢？

/Volumes/DATA/workspace/reactnative/knit/node_modules/react-native-amap-geolocation/lib/ios/AMapGeolocation.m:1:9: fatal error: 'AMapFoundationKit/AMapFoundationKit.h' file not found
#import <AMapFoundationKit/AMapFoundationKit.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Command Analyze failed with a nonzero exit code

**Comment by Mase9527** [comment]
> "react": "16.6.3",
> "react-native": "^0.57.8",
> 
> 将react-native-amap3d及react-native-amap-geolocation使用cocoapods进行安装，pod install后，进行react-native run-ios，会报以下错误；请帮忙看下，怎么解决呢？
> 
> /Volumes/DATA/workspace/reactnative/knit/node_modules/react-native-amap-geolocation/lib/ios/AMapGeolocation.m:1:9: fatal error: 'AMapFoundationKit/AMapFoundationKit.h' file not found
> #import <AMapFoundationKit/AMapFoundationKit.h>
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> Command Analyze failed with a nonzero exit code
我也是遇到了这个问题，请问下应该怎么解决呢

**Comment by qiuxiang** [comment]
用 pod 安装不能 link

**Comment by Mase9527** [comment]
> 用 pod 安装不能 link

谢谢解答，问题解决了，建议在安装文档上也加上这个说明，可能会好一点

**Comment by cskyr** [comment]
> 用 pod 安装不能 link

多谢！切实如你所说，unlink后就正常了

**Comment by wenjianli92** [comment]
android 要link,ios取消link?你怎么unlink的？可以详细点吗？谢谢

**Comment by wenjianli92** [comment]
> 用 pod 安装不能 link

请问，你是怎么用cocoapod安装的，可以看下你的podfile文件吗？
