### ISSUE TITLE
react-native版本问题

### ISSUE THREAD

**Issue by yemengdie** [qiuxiang/react-native-amap-geolocation#76]
react-native版本必须高于0.47吗，react-native 0.45的版本可不可以

**Comment by qiuxiang** [comment]
不是不可以，而是接口不兼容，只能自己手动修改代码

**Comment by yemengdie** [comment]
> 不是不可以，而是接口不兼容，只能自己手动修改代码



> 不是不可以，而是接口不兼容，只能自己手动修改代码

修改哪里的代码  怎么修改
