### ISSUE TITLE
Android permission problem

### ISSUE THREAD

**Issue by zhangwang9li** [qiuxiang/react-native-amap-geolocation#8]
The existence of Android permission problem

my Android bulid 
` compileSdkVersion 27
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.zhgdsystem"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "0.0.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }`
so i do this in ‘init’ checkSelfPermission
`int permission = ActivityCompat.checkSelfPermission(reactContext,
                Manifest.permission.WRITE_EXTERNAL_STORAGE);
        int permissionL = ActivityCompat.checkSelfPermission(reactContext,
                Manifest.permission.ACCESS_COARSE_LOCATION);
        if (permission != PackageManager.PERMISSION_GRANTED || permissionL != PackageManager.PERMISSION_GRANTED) {
            // We don't have permission so prompt the user
            ActivityCompat.requestPermissions(reactContext.getCurrentActivity(), PERMISSIONS_STORAGE,
                    REQUEST_EXTERNAL_STORAGE);
        }
`

**Comment by qiuxiang** [comment]
我不明白你描述的问题和这个项目有什么关系

**Comment by zhangwang9li** [comment]
因为不写写个兼容的话，定不了位
