### ISSUE TITLE
我想询问关于如何封装第三方库

### ISSUE THREAD

**Issue by inkCrazy** [qiuxiang/react-native-amap-geolocation#87]
你好，公司自己有一些需求，需要自己封装一下高德地图，但是在封装iOS的过程中，老是出现问题，一般使用link或者pod安装，但是要么说我的库找不到，要么说高德地图头文件找不到

**Comment by qiuxiang** [comment]
官方文档可以是一个不错的起手，但不够详尽，还需要自己参考内置的库和其他开源库。另外，需要熟悉原生开发，你说的找不到库或头文件，对熟练的原生开发应该是很好解决的

宝强 <notifications@github.com> 于 2019年8月1日周四 上午10:39写道：
