### ISSUE TITLE
iOS逆地理编码

### ISSUE THREAD

**Issue by Yieron** [qiuxiang/react-native-amap-geolocation#96]
iOS确实第一次永远获不到逆地理编码，而且设置setLocatingWithReGeocode(true);后，使用Geolocation.getCurrentPosition也永远获取不到逆地理编码，使用watchPositio后，再调用getCurrentPosition会返回两次

**Comment by Yieron** [comment]
目前我的解决方案是，先设置setLocatingWithReGeocode(true)，然后调用Geolocation .watchPosition()，然后调用Geolocation.clearWatch() 结束监听。这样使用Geolocation.getCurrentPosition就能拿到你地址信息了。

**Comment by ihwf** [comment]
第一次确实获取不到, 照着楼主的方法也获取不到
